FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
# Additional OS packages can be installed here
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
